### PR TITLE
Fix long_activity tool

### PR DESCRIPTION
**Pull request by SavSanta**
# Description
Use negative offset to ensure LONG ACTIVITY NAME is appended to the same column.
Adjust exception message hint to check the first line of CSV for column headers.

### CODE REVIEW

**Comment by stoopidJSON** [comment]
@SavSanta I merged in your other PR so now this has merge conflicts. I'm going to add you to the org so you can submit feature branch PR's to make things a bit easier.

**Comment by SavSanta** [comment]
Okay. I've accepted. Although, I think the merrge conflict is due to this being based on the long_acitvity_tool being branched off an earlier tree. Therefore the server.py (no longer exists) and requirements.txt (updated) are the conflicts. I probably just need to rebase the PR and then re send

**Comment by SavSanta** [comment]
So looks like the earlier early branch that wasnt rebased the problem was in the newly added line that GIT didnt know which to keep. imanually told it which lines to keep and  I believe it should be mergeable now to the long_acitvitiy_tool

**Review by jbixon13 — APPROVED** [review]
csv parsing

**Pull request merged**
